AT.WebApp/Models/AdminViewModel.cs
using AT.Repository.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AT.WebApp.Models
{
    public class AdminViewModel
    {
        public AdminViewModel()
        {
            AdaptationTechniques = new List<AdaptationTechnique>();
        }
        public List<AdaptationTechnique> AdaptationTechniques { get; set; }
        public int Id { get; set; }
        public bool ApplyStatus { get; set; }
        public string EnrichmentTechique { get; set; }
    }
}

AT.WebApp/Models/Alert.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AT.WebApp.Models
{
    public class Alert
    {
        public const string TempDataKey = "TempDataAlerts";

        public string AlertStyle { get; set; }
        public string Message { get; set; }
        public bool Dismissable { get; set; }
    }

    public static class AlertStyles
    {
        public const string Success = "success";
        public const string Information = "info";
        public const string Warning = "warning";
        public const string Danger = "danger";
    }
}

AT.WebApp/Controllers/AdminController.cs
using AT.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AT.Service.Implementations;
using AT.Service.Interfaces;
using AT.Repository.Model;

namespace AT.WebApp.Controllers
{
    public class AdminController : BaseController
    {
        private AdaptationService service = new AdaptationService();

        public AdminController()
        {
        }

        // GET: Adaptation
        public ViewResult Index()
        {
            var model = new AdminViewModel {
                AdaptationTechniques =  service.ListTechniques()
                };

            return View(model.AdaptationTechniques);
        }

        [HttpPost]
        public ViewResult ApplyAdaptationTechniques(IEnumerable<AdaptationTechnique> model)
        {
            if (model.Count()>0)
            {
                var values = new Dictionary<int, bool>();
                foreach (var item in model)
                {
                    values.Add(item.Id, item.ApplyStatus);
                }
                service.ChangesTechniquesToApply(values);
                Success("Applied successfully.", true);
                return View("Index",model);
            }
            else
            {
                Danger("Looks like something went wrong. Please check your form.");
                return View("Index",model);
            }

        }
    }
}

AT.WebApp/Controllers/BaseController.cs
using AT.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AT.WebApp.Controllers
{
    public class BaseController : Controller
    {
        public void Success(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Success, message, dismissable);
        }

        public void Information(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Information, message, dismissable);
        }

        public void Warning(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Warning, message, dismissable);
        }

        public void Danger(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Danger, message, dismissable);
        }

        private void AddAlert(string alertStyle, string message, bool dismissable)
        {
            var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

            alerts.Add(new Alert
            {
                AlertStyle = alertStyle,
                Message = message,
                Dismissable = dismissable
            });

            TempData[Alert.TempDataKey] = alerts;
        }
    }
}

AT.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace AT.WebApp.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
           
            return View();
        }

       // [HttpPost]
        public ActionResult CheckAccessibility(string url)
        {
           return View("AccessibilityForm");
        }


        public ActionResult MakeAdaptation(string url)
        {

           // return View("AdaptationForm");
            return View("ProductView");
        }
    }
}

AT.WebApp/Controllers/LinkController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AT.Repository.Model;

namespace AT.WebApp.Controllers
{
    public class LinkController : BaseController
    {
        private DbModel db = new DbModel();

        // GET: /Link/
        public ActionResult Index()
        {
            return View(db.TextToReadHyperlinks.ToList());
        }

        // GET: /Link/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TextToReadHyperlink texttoreadhyperlink = db.TextToReadHyperlinks.Find(id);
            if (texttoreadhyperlink == null)
            {
                return HttpNotFound();
            }
            return View(texttoreadhyperlink);
        }

        // GET: /Link/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Link/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,HyperlinkText,LanguageCode")] TextToReadHyperlink texttoreadhyperlink,FormCollection form)
        {
            if (ModelState.IsValid)
            {
                string code = form["LanguageDropDownList"].ToString();
                texttoreadhyperlink.LanguageCode = int.Parse(code);
                db.TextToReadHyperlinks.Add(texttoreadhyperlink);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(texttoreadhyperlink);
        }

        // GET: /Link/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TextToReadHyperlink texttoreadhyperlink = db.TextToReadHyperlinks.Find(id);
            if (texttoreadhyperlink == null)
            {
                return HttpNotFound();
            }
            return View(texttoreadhyperlink);
        }

        // POST: /Link/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,HyperlinkText,LanguageCode")] TextToReadHyperlink texttoreadhyperlink)
        {
            if (ModelState.IsValid)
            {
                db.Entry(texttoreadhyperlink).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(texttoreadhyperlink);
        }

        // GET: /Link/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TextToReadHyperlink texttoreadhyperlink = db.TextToReadHyperlinks.Find(id);
            if (texttoreadhyperlink == null)
            {
                return HttpNotFound();
            }
            return View(texttoreadhyperlink);
        }

        // POST: /Link/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TextToReadHyperlink texttoreadhyperlink = db.TextToReadHyperlinks.Find(id);
            db.TextToReadHyperlinks.Remove(texttoreadhyperlink);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AT.WebApp/Views/Admin/Index.cshtml
@model List<AT.Repository.Model.AdaptationTechnique>
@{
    ViewBag.Title = "Adaptation Techniques";
}

@using (Html.BeginForm("ApplyAdaptationTechniques", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    
    <div class="container body-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5>Adaptation techniques</h5>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-condensed table-bordered">
                            @if (Model != null)
                            {
                                for (var i = 0; i < Model.Count; i++)
                                {
                                    <tr>
                                        <td>
                                            @Html.HiddenFor(m => m[i].Id)
                                            @Html.CheckBoxFor(m => m[i].ApplyStatus)
                                            @Html.HiddenFor(m => m[i].EnrichmentTechique)
                                            @Html.DisplayFor(m => m[i].EnrichmentTechique)
                                        </td>
                                        <td>
                                           @if (Html.DisplayFor(m => m[i].EnrichmentTechique).ToString() == (AT.Repository.Enums.AdaptationTechniquesEnum.Link).ToString())
                                           { 
                                               @Html.ActionLink("Configure Hyperlinks","Index","Link")
                                           }
                                        </td>
                                    </tr>
                                }
                            }
                        </table>
                    </div>
                    <div class="panel-footer">
                        @* <input type="button" value="Go Somewhere Else" onclick="location.href='<%: Url.Action("Action", "Controller" ) %>'" />*@
                     
                        <button type="submit" class="btn btn-default">
                            <i class="glyphicon glyphicon-floppy-save"></i> Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

AT.WebApp/Views/Home/AccessibilityForm.cshtml
@{
    Page.Title = "WCAG Results";
}

@{
                string HtmlResult = "";
                string SelectedWCAG = "WCAG2 - Level AA";

                var url = Request.QueryString["url"];
                // If all information is valid, create a new account
                //may want more here for https, etc
                System.Text.RegularExpressions.Regex regex = new System.Text.RegularExpressions.Regex(@"(http://)?(www\.)?\w+\.(com|net|edu|org)");

                if (url == null)
                {
                    Response.Write("< div class='alert alert-danger' style='padding-bottom:1px;padding-top:1px;margin-top:0.1px; margin-bottom:0.1px;' role='alert'>web address must be given</div>");
                }

                if (!regex.IsMatch(url.ToString()))
                {
                    Response.Write("< div class='alert alert-danger' style='padding-bottom:1px;padding-top:1px;margin-top:0.1px; margin-bottom:0.1px;' role='alert'>web address is not correct</div>");

                };

                System.Xml.XmlDocument result = new System.Xml.XmlDocument();

                try
                {

                    result = Check.GetAccessibilityResults(url, SelectedWCAG);
                    HtmlResult = result.InnerXml.ToString();
                }
                catch (Exception ex)
                {
                    HtmlResult = "<div style='font-family:tahoma;font-size:8pt;background-color:red;color:white;font-weight:bold'>Error running checker : " + ex.Message + "</div>";
                    return;
                }

                string[] lines;

                if (result.SelectSingleNode("//status").InnerText == "PASS")
                {
                    return;
                }
                else
                {
                    lines = HtmlResult.Split(new string[] { "\n" }, StringSplitOptions.None);
                    var resultList = result.SelectNodes("//results/result");
                    var numOferrors = result.SelectSingleNode("//NumOfErrors").InnerText;
                    var guidelines = result.SelectSingleNode("//guidelines/guideline").InnerText;

                    int index = 1;

                    //maincontent div
                    HtmlResult = "<div style='padding-left:-10px;margin-left:-10px;'>";

                    HtmlResult += @"<div class='alert alert-info' style='color:#3a87ad; font-family:tahoma;font-size:11pt;padding-bottom:0.5;margin-bottom:0.5px;'> Results: " + SelectedWCAG +
                                  " <div style='float:right;'> <label style='font-family:tahoma;font-size:10pt;'>  Found Errors: " + numOferrors + "</label>";
                    HtmlResult += "</div>  </div>";
                    HtmlResult += @" <div style='padding-bottom:2px;'>
                        <label style='color: #ffffff;text-align:center;background-color: #d9534f; border-color: #d43f3a;width:80px;height:25px;font-family:tahoma;font-size:9pt;'><p style='padding-top: 5px;'>Error</p></label>
                        <label style='color: #ffffff;text-align:center; background-color: #f0ad4e; border-color: #eea236;width:80px;height:25px;font-family:tahoma;font-size:9pt;'><p style='padding-top: 5px;'>Error Code</p></label>
                        <label style='color: #ffffff;text-align:center; background-color: #5bc0de; border-color: #46b8da;width:80px;height:25px;font-family:tahoma;font-size:9pt;'><p style='padding-top: 5px;'>Repair</p></label></div>";

                    for (var i = resultList.Count; i-- > 0;)
                    {
                        System.Xml.XmlNode error = resultList[i];

                        if (error.SelectSingleNode("resultType").InnerText.ToUpper() == "ERROR" || !Check.IgnoreCheckerWarnings)
                        {

                            var errorType = error.SelectSingleNode("resultType").InnerText;
                            var errorLine = Int32.Parse(error.SelectSingleNode("lineNum").InnerText);
                            var errorChar = Int32.Parse(error.SelectSingleNode("columnNum").InnerText);
                            var errorMsg = error.SelectSingleNode("errorMsg").InnerText;
                            var errorTitle = errorMsg.Substring(1 + errorMsg.LastIndexOf("="));
                            var errorSourceCode = error.SelectSingleNode("errorSourceCode").InnerText;
                            var errorRepair = error.SelectSingleNode("repair").InnerText;
                            string chkHtml = string.Empty;

                            if (errorChar > 0)
                            {

                                if (lines.Length > 1)
                                {
                                    //HtmlResult += "<li style='font-family:tahoma;font-size:12pt;background-color:CadetBlue;color:white;font-weight:bold;padding-left:20pt;list-style-type: none'>" + index + ". " + ErrorReporting.FixCodeTags(errorTitle) + " </li>";
                                    //HtmlResult += "<li style='font-family:tahoma;font-size:9pt;background-color:BurlyWood;color:white;font-weight:bold;padding-left:30pt;list-style-type: none'> " + HttpUtility.HtmlEncode(errorSourceCode) + " </li>";
                                    //HtmlResult += "<li style='font-family:tahoma;font-size:9pt;background-color:#339966;color:white;font-weight:bold;padding-left:30pt;list-style-type: none'> " + ErrorReporting.FixCodeTags(errorRepair) + " </li> <br />";

                                    if (errorTitle.Contains("<code>alt</code>"))
                                    {
                                    HtmlResult += @"<br /> <div class='alert alert-danger' style='margin-left:7%;margin-right:8%;padding-bottom:1px;padding-top:1px;margin-top:0.1px; margin-bottom:0.1px;border-color: #b94a48;border-width: 2px;' role='alert'>
                                                       <span class='glyphicon glyphicon-exclamation-sign' aria-hidden='true'></span>&nbsp;&nbsp;" + index + " . " + ErrorReporting.FixCodeTags(errorTitle) + " </div>";
                                    HtmlResult += @"<div class='alert alert-warning' style='margin-left:7%;margin-right:8%;padding-bottom:1px;padding-top:1px;margin-top:0.1px; margin-bottom:0.1px;border-color:#c09853;border-width: 2px;'  role='alert'>
                                                       <span class='glyphicon glyphicon-warning-sign' aria-hidden='true'></span>&nbsp;&nbsp;" + index + " . " + HttpUtility.HtmlEncode(errorSourceCode) + " </div>";
                                    HtmlResult += @"<div class='alert alert-info' style='margin-left:7%;margin-right:8%;padding-bottom:1px;padding-top:1px;margin-top:0.1px; margin-bottom:0.1px;border-color:#3a87ad;border-width: 2px;'  role='alert'>
                                                        <span class='glyphicon glyphicon-ok-sign' aria-hidden='true'></span>&nbsp;&nbsp;" + index + " . " + ErrorReporting.FixCodeTags(errorRepair) + " </div>";
                                    }
                                    else
                                    {
                                        HtmlResult += "<br /> <div class='alert alert-danger' style='margin-left:7%;margin-right:8%;padding-bottom:1px;padding-top:1px;margin-top:0.1px; margin-bottom:0.1px;' role='alert'>" + index + ". " + ErrorReporting.FixCodeTags(errorTitle) + " </div>";
                                        HtmlResult += "<div class='alert alert-warning' style='margin-left:7%;margin-right:8%;padding-bottom:1px;padding-top:1px;margin-top:0.1px; margin-bottom:0.1px;'  role='alert'>" + index + ". " + HttpUtility.HtmlEncode(errorSourceCode) + " </div>";
                                        HtmlResult += "<div class='alert alert-info' style='margin-left:7%;margin-right:8%;padding-bottom:1px;padding-top:1px;margin-top:0.1px; margin-bottom:0.1px;'  role='alert'>" + index + ". " + ErrorReporting.FixCodeTags(errorRepair) + " </div>";

                                    }

                                   index++;
                               }

                        }
                 }

            //End maincontent div
            HtmlResult += "</div>";
        }
    }
}


    <a name="administration"></a>
        <div class="container">
          
            <div class="row">
                <div class="col-lg-12">
                        @{
                            @Html.Raw(@HtmlResult)
                        }
                </div>
            </div>
        </div>

AT.WebApp/Views/Home/AdaptationForm.cshtml
@{
    Page.Title = "Adaptation";
    //Layout = "Your Layout Page goes here";

}

<style>
    a.skip-main {
        left: -999px;
        position: absolute;
        top: auto;
        width: 1px;
        height: 1px;
        overflow: hidden;
        z-index: -999;
    }

        a.skip-main:focus, a.skip-main:active {
            color: #fff;
            background-color: #000;
            left: auto;
            top: auto;
            width: 30%;
            height: auto;
            overflow: auto;
            margin: 10px 35%;
            padding: 5px;
            border-radius: 15px;
            border: 4px solid yellow;
            text-align: center;
            font-size: 1.2em;
            z-index: 999;
        }

         .skip {
        position: absolute;
        top: -1000px;
        left: -1000px;
        height: 1px;
        width: 1px;
        text-align: left;
        overflow: hidden;
    }
    
    a.skip:active, 
    a.skip:focus, 
    a.skip:hover {
        left: 0; 
        top: 0;
        width: auto; 
        height: auto; 
        overflow: visible; 
    }
</style>
    @{
        var url = Request.QueryString["url"] == null ? "" : Request.QueryString["url"].ToString();
        var content = AdaptationUtil.GetHtmlDocument(url);
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @Html.Raw(content.ToString())
                </div>
            </div>
         </div>
            @*HttpWebRequest req = (HttpWebRequest)HttpWebRequest.Create(url);
                req.Method = "GET";
                req.UserAgent = "Mozilla/5.0 (Windows; U; MSIE 9.0; WIndows NT 9.0; en-US))";
                req.Headers[HttpRequestHeader.AcceptEncoding] = "gzip, deflate";
                req.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip;
                string source;
                using (StreamReader reader = new StreamReader(req.GetResponse().GetResponseStream()))
                {
                    source = reader.ReadToEnd();
                }
                HtmlAgilityPack.HtmlDocument doc = new HtmlAgilityPack.HtmlDocument();
                doc.LoadHtml(source);
                @Html.Raw(WebUtility.HtmlDecode(source));*@

            }

AT.WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";

   
}
<script type='text/javascript'>

                                $( document ).ready(function() {
                                    $("#accLink").hover(function () {
                                        var fakedUri = $("#accLink").prop("href");
                                        var route = fakedUri.replace("xxxx", $("#txtUrl").val());
                                        $("#accLink").attr("href", route);

                                    });
                                    $("#accLink").click(function () {
                                        var fakedUri = $("#accLink").prop("href");
                                        var route = fakedUri.replace("xxxx", $("#txtUrl").val());
                                        $("#accLink").attr("href", route);
                                    });

                                    $("#adpLink").hover(function () {
                                        var fakedUri = $("#adpLink").prop("href");
                                        var route = fakedUri.replace("xxxx", $("#txtUrl").val());
                                        $("#adpLink").attr("href", route);
                                    });
                                    $("#adpLink").click(function () {
                                        var fakedUri = $("#adpLink").prop("href");
                                        var route = fakedUri.replace("xxxx", $("#txtUrl").val());
                                        $("#adpLink").attr("href", route);
                                    });

                                });
</script>

<!-- Header -->
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message" align="center">
                    <h1>Accessibility Page</h1>
                    <h3>Put link of website for checking accessibility</h3>
                    <hr class="intro-divider">
                    <input type="text" class="form-control" style="width:400px;" id="txtUrl" name="txtUrl" value="http://www.w3schools.com" />
                    <hr class="intro-divider">
                     <ul class="list-inline intro-social-buttons">
                        <li>
                             @Html.ActionLink(" Check by WCAG",
                                    "CheckAccessibility",
                                    "Home",new  { url = "xxxx" },
                                    new { @id = "accLink", @class = "btn btn-default btn-lg fa fa-cog",@style="font-size:19px;" })
                         </li>
                        <li>
                             @Html.ActionLink(" Make Adaptation",
                                    "MakeAdaptation",
                                    "Home", new { url = "xxxx" },
                                    new {@id="adpLink", @class = "btn btn-default btn-lg fa fa-globe", @style = "font-size:19px;" })
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->

</div>
<!-- /.intro-header -->
<!-- Page Content -->

AT.WebApp/Views/Link/Create.cshtml
@model AT.Repository.Model.TextToReadHyperlink

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="container body-content">
    <div class="row">
        <div class="col-lg-12">
            <h2>Create</h2>
            <div class="form-horizontal">
                <h4>TextToReadHyperlink</h4>
                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.HyperlinkText, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.HyperlinkText)
                        @Html.ValidationMessageFor(model => model.HyperlinkText)
                    </div>
                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.LanguageCode, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LanguageCode)
                        @Html.ValidationMessageFor(model => model.LanguageCode)
                    </div>
                </div>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.LanguageCode, new { @class = "control-label col-md-2" })
                    <div class="col-md-2">
                       
                        @Html.DropDownList("LanguageDropDownList",
                           EnumHelper.GetSelectList(typeof(AT.Repository.Enums.LanguageCodes)),
                           "Select Language",
                           new { @class = "form-control" })
                    </div>
                </div>
             

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
            </div>
        </div>
        </div>
}

AT.WebApp/Views/Link/Delete.cshtml
@model AT.Repository.Model.TextToReadHyperlink

@{
    ViewBag.Title = "Delete";
}

<div class="container body-content">
    <div class="row">
        <div class="col-lg-12">

            <h2>Delete</h2>

            <h3>Are you sure you want to delete this?</h3>
            <div>
                <h4>TextToReadHyperlink</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.HyperlinkText)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.HyperlinkText)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.LanguageCode)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.LanguageCode)
                    </dd>

                </dl>

                @using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
    }
            </div>

</div>
        </div>
    </div>

AT.WebApp/Views/Link/Details.cshtml
@model AT.Repository.Model.TextToReadHyperlink

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TextToReadHyperlink</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HyperlinkText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HyperlinkText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LanguageCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LanguageCode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AT.WebApp/Views/Link/Edit.cshtml
@model AT.Repository.Model.TextToReadHyperlink

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TextToReadHyperlink</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.HyperlinkText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HyperlinkText)
                @Html.ValidationMessageFor(model => model.HyperlinkText)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LanguageCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LanguageCode)
                @Html.ValidationMessageFor(model => model.LanguageCode)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AT.WebApp/Views/Shared/_Alerts.cshtml
@using AT.WebApp.Models
@{
    var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

    if (alerts.Any())
    {
        <hr />
    }

    foreach (var alert in alerts)
    {
        var dismissableClass = alert.Dismissable ? "alert-dismissable" : null;
        <div class="container body-content">
            <div class="alert alert-@alert.AlertStyle @dismissableClass">
                @if (alert.Dismissable)
                {
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                }
                @Html.Raw(alert.Message)
            </div>
            </div>
            }
            }